import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import $ from 'jquery';

export default function Home() {
  $(document).on("ready", function(){

    $(".bar").on("click", function(){
      $(this).toggleClass("selected");
    })
  
  
    var barIndex = 0;
  
    $("#play").on("click", function(){
  
      $(".bar").eq(barIndex).removeClass("current");
  
      if(barIndex < 7)
        barIndex++;
      else
        barIndex = 0;
  
      $(".bar").eq(barIndex).addClass("current");
    })
  
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>Beat js - create beats or website music without using audio files</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
         Beat js
        </h1>
        <div className="sequencer">
          <div className="bars-row" id="row1">
            <div className="bar current" id="row1-bar1"></div>
            <div className="bar selected" id="row1-bar2"></div>
            <div className="bar" id="row1-bar3"></div>
            <div className="bar" id="row1-bar4"></div>
            <div className="bar" id="row1-bar5"></div>
            <div className="bar" id="row1-bar6"></div>
            <div className="bar" id="row1-bar7"></div>
            <div className="bar" id="row1-bar8"></div>
          </div>
        </div>
        <button id="play">Play</button>
        
        
      </main>

      
    </div>
  )
}
